# Generated by Django 5.2.7 on 2025-11-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
    ]
