# Generated by Django 5.2.7 on 2025-11-10 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('vida_util', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id_recepcion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Des_Recepcion',
            fields=[
                ('id_detalle', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=10)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recepcion', to='main.producto')),
                ('idrecepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main.recepcion')),
            ],
        ),
    ]
