# Generated by Django 5.2.7 on 2025-11-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id_recepcion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Det_Recepcion',
            fields=[
                ('id_detalle', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=10)),
                ('lote', models.CharField(max_length=30, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=60)),
                ('idproducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recepcion', to='main.producto')),
                ('idrecepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main.recepcion')),
            ],
        ),
    ]
