# Generated by Django 5.2.7 on 2025-11-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producto_recepcion_des_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='des_recepcion',
            name='lote',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='des_recepcion',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
