# Generated by Django 5.2.7 on 2025-11-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recepcion_det_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='det_recepcion',
            name='unidad',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
