# Generated by Django 5.2.7 on 2025-11-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_det_recepcion_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='det_recepcion',
            name='unidad',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
